title = "WORLD WIDE LULU"
base_url = "https://blog.lulurl.fr"

default_language = "fr"

theme = "duckquill"

compile_sass = true
minify_html = true
generate_feeds = true

feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true

author = "lulu"

taxonomies = [{ name = "tags", feed = true }]

[search]
index_format = "fuse_json"

[markdown]
smart_punctuation = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
light_theme = "solarized-light"
dark_theme = "solarized-dark"

[languages.en-US]
title = "WORLD WIDE LULU"
generate_feeds = true
build_search_index = true
taxonomies = [{ name = "tags", feed = true }]

[extra]
accent_color = "#ffa348"

emoji_favicon = "🪆"

date_format = "%A %e %B %Y" # Vendredi 8 Octobre 2023

issues_url = ""

source_url = "https://github.com/lusinge/site-perso"

styles = ["custom.css"]

fix_contrast = true

show_reading_time = true

show_copy_button = true

show_share_button = true

show_backlinks = true

[extra.nav]
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  { name = "Extras", menu = [
    { url = "@/australie/uts/_index.md", name = "UTS" },
  ] },
  # { url = "@/art/_index.md", name = "Art" },

]

show_feed = true

show_theme_switcher = true

show_repo = true

[extra.footer]
show_copyright = true

show_powered_by = true

show_source = false
